from __future__ import annotations

import sys

import cv2
import matplotlib.pyplot as plt
import numpy as np

from PySide6.QtWidgets import QApplication

from core.calibration.image_loader import load_image
from core.roi.selector import ROISelector
from core.detection.silhouette_detector import (
    detect_silhouette_candidates,
)


IMAGE_PATH = "test_images/001-20260730170838506.png"


def draw_candidates(
    image: np.ndarray,
    candidates,
) -> np.ndarray:
    """
    Draw ranked candidate contours on the ROI.
    """

    output = image.copy()

    for index, candidate in enumerate(
        candidates
    ):

        contour = candidate.contour

        # ------------------------------------------------------
        # Candidate colour is intentionally generated by OpenCV.
        # This is only a debug visualization.
        # ------------------------------------------------------

        if index == 0:
            color = (0, 255, 0)
        elif index == 1:
            color = (255, 0, 0)
        elif index == 2:
            color = (0, 0, 255)
        else:
            color = (255, 255, 0)

        cv2.drawContours(
            output,
            [contour],
            -1,
            color,
            3,
        )

        x, y, w, h = (
            cv2.boundingRect(
                contour
            )
        )

        label = (
            f"#{index + 1} "
            f"{candidate.score:.3f}"
        )

        cv2.putText(
            output,
            label,
            (x, max(20, y)),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            color,
            2,
            cv2.LINE_AA,
        )

    return output


def print_candidates(
    candidates,
) -> None:

    print()
    print("=" * 80)
    print("SILHOUETTE CANDIDATES")
    print("=" * 80)

    for index, candidate in enumerate(
        candidates,
        start=1,
    ):

        x, y, w, h = (
            candidate.bounding_box
        )

        print()
        print(
            f"Candidate #{index}"
        )

        print(
            f"  score                : "
            f"{candidate.score:.4f}"
        )

        print(
            f"  area ratio           : "
            f"{candidate.area_ratio:.4f}"
        )

        print(
            f"  width ratio          : "
            f"{candidate.width_ratio:.4f}"
        )

        print(
            f"  height ratio         : "
            f"{candidate.height_ratio:.4f}"
        )

        print(
            f"  solidity             : "
            f"{candidate.solidity:.4f}"
        )

        print(
            f"  Hessian support      : "
            f"{candidate.hessian_support:.4f}"
        )

        print(
            f"  inside target        : "
            f"{candidate.inside_target_support:.4f}"
        )

        print(
            f"  outside white       : "
            f"{candidate.outside_white_support:.4f}"
        )

        print(
            f"  perimeter            : "
            f"{candidate.perimeter:.2f}"
        )

        print(
            f"  bounding box         : "
            f"({x}, {y}, {w}, {h})"
        )

        print(
            f"  boundary touches    : "
            f"{candidate.boundary_touch_count}"
        )

        print(
            f"  boundary ratio      : "
            f"{candidate.boundary_touch_ratio:.4f}"
        )


def main():

    # ---------------------------------------------------------
    # Qt
    # ---------------------------------------------------------

    app = QApplication.instance()

    if app is None:
        app = QApplication(sys.argv)

    # ---------------------------------------------------------
    # Load
    # ---------------------------------------------------------

    image_data = load_image(
        IMAGE_PATH
    )

    # ---------------------------------------------------------
    # ROI selection
    # ---------------------------------------------------------

    selector = ROISelector(
        image_data
    )

    result = selector.exec()

    if result != selector.DialogCode.Accepted:
        print(
            "ROI selection cancelled."
        )
        return

    roi = selector.roi

    if roi is None:
        print(
            "No ROI selected."
        )
        return

    # ---------------------------------------------------------
    # Silhouette analysis
    # ---------------------------------------------------------

    detection = (
        detect_silhouette_candidates(
            image_data,
            roi,
            hessian_threshold=250,
            max_candidates=10,
        )
    )

    # ---------------------------------------------------------
    # ROI
    # ---------------------------------------------------------

    cropped = roi.crop(
        image_data.image
    )

    cropped_rgb = cv2.cvtColor(
        cropped,
        cv2.COLOR_BGR2RGB,
    )

    # ---------------------------------------------------------
    # Candidate visualization
    # ---------------------------------------------------------

    candidate_image = (
        draw_candidates(
            cropped,
            detection.candidates,
        )
    )

    candidate_rgb = cv2.cvtColor(
        candidate_image,
        cv2.COLOR_BGR2RGB,
    )

    # ---------------------------------------------------------
    # Print numerical results
    # ---------------------------------------------------------

    print_candidates(
        detection.candidates
    )

    # ---------------------------------------------------------
    # Visualization
    # ---------------------------------------------------------

    fig, axes = plt.subplots(
        2,
        3,
        figsize=(16, 10),
    )

    axes[0, 0].imshow(
        cropped_rgb
    )

    axes[0, 0].set_title(
        "Selected ROI"
    )

    axes[0, 1].imshow(
        detection.hessian_mask,
        cmap="gray",
    )

    axes[0, 1].set_title(
        "Hessian Evidence"
    )

    axes[0, 2].imshow(
        detection.inside_target_mask,
        cmap="gray",
    )

    axes[0, 2].set_title(
        "Inside Target Evidence"
    )

    axes[1, 0].imshow(
        detection.white_mask,
        cmap="gray",
    )

    axes[1, 0].set_title(
        "White Evidence"
    )

    axes[1, 1].imshow(
        candidate_rgb
    )

    axes[1, 1].set_title(
        "Ranked Candidates"
    )

    # ---------------------------------------------------------
    # Best candidate only
    # ---------------------------------------------------------

    axes[1, 2].imshow(
        cropped_rgb
    )

    if detection.candidates:

        best = (
            detection.candidates[0]
        )

        best_image = cropped.copy()

        cv2.drawContours(
            best_image,
            [best.contour],
            -1,
            (255, 0, 0),
            3,
        )

        best_rgb = cv2.cvtColor(
            best_image,
            cv2.COLOR_BGR2RGB,
        )

    axes[1, 2].imshow(best_rgb)

    axes[1, 2].set_title(
        "Best Candidate"
    )

    for ax in axes.flat:
        ax.axis("off")

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()